### ISSUE TITLE
Issue opening on Ubuntu 23.10

### ISSUE THREAD

**Issue by DGxInfinitY** [Martichou/rquickshare#52]
I installed the .deb package and it wouldn't open. I tried opening from the terminal with the `r-quickshare` command and this is the output.

`thread 'main' panicked at /home/runner/work/rquickshare/rquickshare/core_lib/src/hdl/ble.rs:24:49:
called `Result::unwrap()` on an `Err` value: Other(DbusError(D-Bus error: Failed to activate service 'org.bluez': timed out (service_start_timeout=25000ms) (org.freedesktop.DBus.Error.TimedOut)))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

here is with the environment variable

`stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
   3: rquickshare::main::{{closure}}
   4: tokio::runtime::park::CachedParkThread::block_on
   5: tokio::runtime::runtime::Runtime::block_on
   6: rquickshare::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.`

It is worth noting that I do not have any Bluetooth hardware plugged into this computer and that might be why it is unable to call bluez.

Any help would be appreciated.

**Comment by DGxInfinitY** [comment]
Oh man. I accidentally tried to use v0.1 but v0.4.1 worked perfectly! Thanks!
