### ISSUE TITLE
the activity workaround doesn't work

### ISSUE THREAD

**Issue by Nyha454** [Martichou/rquickshare#57]
i am on an S21 Ultra Android 14, my device was not showing on my laptop so i tried the activity workaround i plugged my phone with usb debugging and used this command "adb shell am start -n com.google.android.gms/.nearby.sharing.ReceiveSurfaceActivity"
 it would give me this output :
Starting: Intent { cmp=com.google.android.gms/.nearby.sharing.ReceiveSurfaceActivity }
Error type 3
Error: Activity class {com.google.android.gms/com.google.android.gms.nearby.sharing.ReceiveSurfaceActivity} does not exist.

so i tried one of the shortcut makers and none of them would show the activity they would only show com.google.android.gms.nearby.sharing.InternalReceiveSurfaceActivity

and when i run it it gives me this output:

Starting: Intent { cmp=com.google.android.gms/.nearby.sharing.InternalReceiveSurfaceActivity }

Exception occurred while executing 'start':
java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.google.android.gms/.nearby.sharing.InternalReceiveSurfaceActivity } from null (pid=26681, uid=2000) not exported from uid 10248
        at com.android.server.wm.ActivityTaskSupervisor.checkStartAnyActivityPermission(ActivityTaskSupervisor.java:1328)
        at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1377)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:1000)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1953)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1812)
        at com.android.server.am.ActivityManagerService.startActivityAsUserWithFeature(ActivityManagerService.java:3814)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:765)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:248)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:11891)
        at android.os.Binder.shellCommand(Binder.java:1104)
        at android.os.Binder.onTransact(Binder.java:914)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:5720)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3195)
        at android.os.Binder.execTransactInternal(Binder.java:1380)
        at android.os.Binder.execTransact(Binder.java:1311)

tried the second method but i didn't understand it and it just wouldn't work tried to launch it with intent, instant intent, intent launcher. the only one that "kinda" made sense  was intent and it wouldn't launch it and it would tell me couldn't find explicit activity class blah blah blah.

and the google files app wouldn't let me receive or send telling me it isn't available for my device

**Comment by Martichou** [comment]
That's strange. Seems like it's broken from an update.

- https://github.com/grishka/NearDrop/issues/144
- https://github.com/grishka/NearDrop/issues/153

So until the BLE advertisement (still WIP) is fixed in RQuickShare, I have no workaround for that :/
